#### IMPORTANT note: axis=0 applies function to each column, axis=1 applies function to each row

##### Ref: https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [18]:
import numpy as np

##### see version

In [19]:
np.__version__

'1.25.0'

##### create 1D array of numbers 0 to 9

In [20]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### create array filled with specified values, shape and data type

In [21]:
barr = np.full(shape=(3, 3), fill_value=True, dtype=bool)
barr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

##### extract elements satisfying given condition

In [22]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  # input
odd_arr = np.where(arr % 2)
odd_arr
odd_arr = arr[arr % 2 == 1]
odd_arr

array([1, 3, 5, 7, 9])

##### replace odd elements with -1

In [23]:
new_arr = np.where(arr % 2 == 1, -1, arr)
new_arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

##### reshape array

In [24]:
arr = np.arange(10) # input
new_arr = arr.reshape(2,5)
new_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

##### stack arrays vertically and horizontally

In [25]:
a = np.arange(10).reshape(2,-1)     # input
b = np.repeat(1, 10).reshape(2,-1)  # input
v_arr = np.concatenate((a, b), axis=0)
h_arr = np.concatenate((a, b), axis=1)
# v_arr
h_arr

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

##### generate custom sequences

In [26]:
arr = np.array([1,2,3]) # input
rep = np.repeat(arr, 3)
t = np.tile(arr, 3)
# test = np.tile(arr, (3,2))
seq = np.concatenate((rep, t))
seq

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

##### set operations - https://numpy.org/doc/stable/reference/routines.set.html

##### get common items (intersection) between 2 arrays

In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])     # input
b = np.array([7,2,10,2,7,4,9,4,9,8])    # input
com = np.intersect1d(a, b)
#com

##### remove elements from a that are present in b

In [28]:
sub = np.setdiff1d(a, b)
sub

array([1, 3, 5, 6])

##### find positions (indices) where elements of a and b are same

In [29]:
eq = np.where(a == b)
eq

(array([1, 3, 5, 7]),)

##### extract numbers from a given range

In [30]:
a = np.array([2, 6, 1, 9, 10, 3, 27])   # input
arr = a[(a >= 5) & (a <= 10)]
arr = a[np.where((a >= 5) & (a <= 10))]     # where with only condition provided - https://numpy.org/doc/stable/reference/generated/numpy.where.html#numpy.where
arr

array([ 6,  9, 10])

##### get elementwise maximum

In [31]:
a = np.array([5, 7, 9, 8, 6, 4, 5])     # input
b = np.array([6, 3, 4, 8, 9, 7, 1])     # input

my_max = lambda val1, val2: max(val1, val2)
pair_max = np.vectorize(my_max, otypes='f')         # otypes as string (float)
pair_max = np.vectorize(my_max, otypes=[float])     # otypes as list (float)

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

##### to check 2 equal arrays

In [32]:
a = np.full(shape=(3, 2), fill_value=4, dtype=int)
b = np.full(shape=(3, 2), fill_value=4, dtype=int)

np.all(a == b)

True

##### insert

In [33]:
a = np.array([[1, 1], [2, 2], [3, 3]])
np.insert(a, 1, 5)
np.insert(a, 1, 5, axis=1)
np.insert(a, [1], [[4],[5],[6]], axis=1)
np.insert(a.flatten(), [2, 2], [5, 6])
np.insert(a.flatten(), slice(2, 4), [5, 6])

array([1, 1, 5, 2, 6, 2, 3, 3])

##### Usage of argsort

In [34]:
a = np.array([3, 1, 2])
a[np.argsort(a)]    # returns sorted array
# np.argsort(a)

array([1, 2, 3])